GET http://localhost:8080/transactions

###
POST http://localhost:8080/transactions
Content-Type: application/json

{
  "totalAmount": 238,
  "paymentType": "PAYPAL",
  "paymentStatus": "NEW",
  "items": [
    {
      "name": "bike",
      "price": 208,
      "quantity": 1
    },
    {
      "name": "shoes",
      "price": 30,
      "quantity": 1
    }
  ]
}

> {%
    client.global.set("payment_id", response.body.id);
%}

###
PATCH http://localhost:8080/transactions/{{payment_id}}
Content-Type: application/json

{
  "paymentStatus": "CANCELED"
}

###
GET http://localhost:8080/transactions/{{payment_id}}
